server:
  port: 8088

spring:
  application:
    name: shipping-service

  datasource:
    url: jdbc:postgresql://localhost:5432/shipping_db
    username: nguyendat
    password: nguyendat
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


# Default shipping settings
shipping:
  default-weight: 1000
  default-length: 20
  default-width: 15
  default-height: 10

logging:
  level:
    root: INFO
    com.ecommerce: DEBUG

